version: '3'

services:
  fschatapiserver:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "7860:7860"
      - "8000:8000"

    volumes:
      - ./cache:/root/.cache
      - ./content:/root/content

    command:
      /bin/sh /root/content/apiserver.sh

